### ISSUE TITLE
64bit

### ISSUE THREAD

**Issue by caspahouzer** [benbahrenburg/LocalNotify#12]
Could you please update for 64bit?

**Comment by AppWerft** [comment]
same question, depending 'bencoding.dictionary' too.
+1

**Comment by simensol** [comment]
+1

**Comment by AppWerft** [comment]
the newest version of local notify works without 'bencoding.dictionary' too.  The üroblem is solved ;-)

**Comment by benbahrenburg** [comment]
PR merged which includes x64
