### ISSUE TITLE
Register for Local Notifications

### ISSUE THREAD

**Issue by simensol** [benbahrenburg/LocalNotify#14]
When using this module, do I need to [register the app](http://docs.appcelerator.com/titanium/3.0/#!/guide/iOS_Local_Notifications-section-40929226_iOSLocalNotifications-RegisterforLocalNotifications) to use the local notification services in iOS 8?

**Comment by benbahrenburg** [comment]
It is only recommended that you read local notifications using this module. In order to read, you would have first registered, otherwise there would be nothing to consume.
