### ISSUE TITLE
Method depreciated please use the Ti.App.iOS.scheduleLocalNotification

### ISSUE THREAD

**Issue by macCesar** [benbahrenburg/LocalNotify#16]
Hi there... I'm getting this message:

Method depreciated please use the Ti.App.iOS.scheduleLocalNotification

I'm running the latest SDK 4.1.0.GA

Cheers!!

**Comment by benbahrenburg** [comment]
Hello, correct. You need to use the core Titanium SDK methods to create notifications.  The API you should be using is mentioned in the message.

**Comment by macCesar** [comment]
So, I no longer need your module???

**Comment by benbahrenburg** [comment]
You can still use the module to query notifications. But, I would highly recommend using the Titanium Core feature to schedule notifications.  AppC has enhanced the API to provide support for the new notification features in iOS8 and above.

The API is the same between my module and the native Ti SDK.  This should make moving your app over a breeze.

**Comment by macCesar** [comment]
Thanks Ben... That is what I read in other posts!!

But even in your sample... You are still using this:

var notify = require('bencoding.localnotify');
...
...
...
notify.scheduleLocalNotification({
	alertBody:"This is a test of benCoding.localNotify",
	alertAction:"Just a test",
	userInfo:{"id":1,"hello":"world","category":"foo"},
	badge:11, //Then needs to be a number
	//sound:"pop.caf", //Copy file from KitchenSink example if you want to try this out
	date:new Date(new Date().getTime() + 60000) 
});
alert("LocalNotification Scheduled");

I think you should change it, to clarify the correct procedure...

That is only a suggestion. ;-)

Thanks again, I have my App working again!!!
