### ISSUE TITLE
Notifications not being created on Ti SDK 4.1

### ISSUE THREAD

**Issue by spudatron** [benbahrenburg/LocalNotify#17]
For some reason the notifications are not being scheduled on the latest SDK. I tested with my original code as well using your example code and none are being created.

**Comment by spudatron** [comment]
I didn't know about this http://docs.appcelerator.com/platform/latest/#!/guide/iOS_Local_Notifications, I am assuming this will sort my issue.

**Comment by benbahrenburg** [comment]
Hello,
Since the native Ti SDK notifications are now working and provide more functionality then localnotify, I'm recommending you only use Localnotify to query notifications already saved.
